package ru.safeai.gateway.model.domain;

public enum ModelRouteReason {
    POLICY_DEFAULT,
    RUNTIME_ONLY_MATCH,
    LEGACY_RUNTIME_FALLBACK,

    MODEL_NOT_ALLOWED,
    MODEL_DENIED,
    MODEL_NOT_FOUND,
    MODEL_DISABLED,
    RUNTIME_MISMATCH,
    CAPABILITY_UNSUPPORTED,
    INPUT_LIMIT_EXCEEDED,
    OUTPUT_LIMIT_EXCEEDED,
    PRICING_INCOMPLETE,
    TRAINING_POLICY_UNSATISFIED,
    RETENTION_POLICY_UNSATISFIED,
    REQUEST_COST_LIMIT_EXCEEDED,
    MONTHLY_BUDGET_EXCEEDED,
    MONTHLY_BUDGET_UNVERIFIABLE
}
