# infra/nginx/nginx.conf

server {
    listen 80;
    server_name your-domain.com;

    location /actuator/health {
        proxy_pass http://backend:8080;
    }

    location /actuator/prometheus {
        allow 172.18.0.0/16;
        deny all;

        proxy_pass http://backend:8080;
    }

    location /actuator/ {
        deny all;
    }

    location / {
        proxy_pass http://backend:8080;
    }
}