package ru.safeai.gateway.audit;

public enum AuditEventType {
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,

    CHAT_CREATED,
    CHAT_ARCHIVED,
    CHAT_MESSAGE_SENT,
    AI_RESPONSE_RECEIVED,
    AI_RESPONSE_FAILED,

    USER_CREATED,
    USER_UPDATED,
    USER_ENABLED_CHANGED,
    USER_ROLES_CHANGED,
    USER_PASSWORD_RESET,
    USER_PERMANENTLY_DELETED,

    ORGANIZATION_CREATED,
    ORGANIZATION_NAME_CHANGED,
    ORGANIZATION_ENABLED_CHANGED,

    RATE_LIMIT_EXCEEDED,
    SECURITY_REFRESH_REUSE_DETECTED,
    USER_LOGOUT,

    KNOWLEDGE_BASE_CREATED,
    KNOWLEDGE_BASE_UPDATED,
    KNOWLEDGE_BASE_MEMBER_ADDED,
    KNOWLEDGE_BASE_MEMBER_UPDATED,
    KNOWLEDGE_BASE_MEMBER_REMOVED,

    KNOWLEDGE_DOCUMENT_CREATED,
    KNOWLEDGE_DOCUMENT_UPDATED,
    KNOWLEDGE_DOCUMENT_VERSION_UPLOADED,
    KNOWLEDGE_DOCUMENT_DOWNLOADED,

    KNOWLEDGE_REINDEX_REQUESTED,
    KNOWLEDGE_INGESTION_READY,
    KNOWLEDGE_INGESTION_FAILED,
    KNOWLEDGE_RETRIEVAL_COMPLETED,
    KNOWLEDGE_EVALUATION_COMPLETED,
    KNOWLEDGE_ANSWER_GENERATED,

    MODEL_CATALOG_VERSION_CREATED,
    MODEL_POLICY_VERSION_CREATED,
    MODEL_ROUTE_DECIDED,
    MODEL_ROUTE_DENIED
}
