package ru.safeai.gateway.ai.exception;

public enum AiProviderErrorType {
    CONNECT_FAILURE,
    TIMEOUT,
    RATE_LIMITED,
    OVERLOADED,
    QUOTA_EXHAUSTED,
    BILLING_ERROR,
    AUTHENTICATION,
    PERMISSION_DENIED,
    INVALID_REQUEST,
    RESPONSE_TOO_LARGE,
    PROTOCOL_ERROR,
    SERVER_ERROR,
    UNKNOWN
}
