package ru.safeai.gateway.chat.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.util.UUID;

/**
 * clientRequestId is a mandatory idempotency key generated by the client
 * before the first attempt and reused for every retry of the same message.
 */
public record SendMessageRequest(
        @NotBlank
        @Size(max = 100_000)
        String content,

        @NotNull
        UUID clientRequestId
) {
}
